language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - pip install -r requirements.txt -r requirements-dev.txt -e .
  - pip install coverage coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install importlib; fi"

services:
  - mongodb

script: py.test --cov flask_security --cov-report term-missing --pep8 --flakes

after_script:
  - coveralls

branches:
  only:
    - develop
